services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: langconnect 
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpassword 
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8099:8080
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
